name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [1.8, 11]
        runtime: [ol, olbeta, wlp]
        runtime_version: [22.0.0.8, 22.0.0.9-beta]
        exclude:
        - runtime: olbeta
          runtime_version: 22.0.0.8
        - runtime: ol
          runtime_version: 22.0.0.9-beta
        - runtime: wlp
          runtime_version: 22.0.0.9-beta

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn verify -Druntime="${{ matrix.runtime }}" -DruntimeVersion="${{ matrix.runtime_version }}"
