name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 7
      matrix:
        os: [ubuntu-latest, windows-latest]
        java: [8, 11, 17]
        runtime: [ol, olbeta, wlp]
        runtime_version: [22.0.0.10, 22.0.0.11-beta]
        exclude:
        - runtime: olbeta
          runtime_version: 22.0.0.10
        - runtime: ol
          runtime_version: 22.0.0.11-beta
        - runtime: wlp
          runtime_version: 22.0.0.11-beta
        - java: 8
          runtime_version: 22.0.0.11-beta

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}
    - name: Build with Maven
      run: mvn verify -Druntime="${{ matrix.runtime }}" -DruntimeVersion="${{ matrix.runtime_version }}"
