name: Java CI with Maven

on:
  push:
    branches: [ 1.x-maintenance ]
  pull_request:
    branches: [ 1.x-maintenance ]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      max-parallel: 5
      matrix:
        os: [ubuntu-latest, windows-latest]
        runtime: [ol, wlp]
        runtime_version: [21.0.0.3, 20.0.0.12]
        java: [11, 8]
        exclude:
        - java: 8
          runtime_version: 20.0.0.12

    steps:
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: ${{ matrix.java }}
    - name: Checkout liberty-arquillian
      uses: actions/checkout@v2
    - name: Build with Maven
      run: mvn verify -Druntime="${{ matrix.runtime }}" -DruntimeVersion="${{ matrix.runtime_version}}"